#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/../../../../../pbf@3.3.0/node_modules/pbf/bin/pbf" "$@"
else
  exec node  "$basedir/../../../../../pbf@3.3.0/node_modules/pbf/bin/pbf" "$@"
fi
